# version: '3'
# services:
#   central:
#     build: .
#     container_name: central
#     ports:
#       - "5000:5000"
#     environment:
#       - MODE=central.py
#       - PORT=5000

#   peer1:
#     build: .
#     container_name: peer1
#     ports:
#       - "5001:5001"
#     environment:
#       - MODE=peer.py
#       - PORT=5001

#   peer2:
#     build: .
#     container_name: peer2
#     ports:
#       - "5002:5002"
#     environment:
#       - MODE=peer.py
#       - PORT=5002
version: '3'
services:
  central:
    build: ./backend
    container_name: central
    ports:
      - "5000:5000"
    environment:
      - MODE=central.py
      - PORT=5000
      - AUTO_REGISTER_PEERS=true 

  peer1:
    build: ./backend
    container_name: peer1
    ports:
      - "5001:5001"
    environment:
      - MODE=peer.py
      - PORT=5001

  peer2:
    build: ./backend
    container_name: peer2
    ports:
      - "5002:5002"
    environment:
      - MODE=peer.py
      - PORT=5002

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - central